on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "Team-HireNova/website"
          source_branch: "main"
          destination_repo: "bernatfogarasi/hirenova-website-mirror"
          destination_branch: "main"
